version: '3'
services:
  redis:
    image: redis
  app:
    depends_on:
      - redis
    links:
      - redis
    build: .
    environment:
      - AUTOPILOT_API_KEY # This value is picked up from host env variable (if defined) OR alternatively use secrets (preferred to use "Secrets" approch)
    ports:
      - "8080:8080"
