// Code generated by MockGen. DO NOT EDIT.
// Source: store.go

// Package mock_store is a generated GoMock package.
package mock_store

import (
	models "addressbook/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockContactCache is a mock of ContactCache interface
type MockContactCache struct {
	ctrl     *gomock.Controller
	recorder *MockContactCacheMockRecorder
}

// MockContactCacheMockRecorder ßis the mock recorder for MockContactCache
type MockContactCacheMockRecorder struct {
	mock *MockContactCache
}

// NewMockContactCache creates a new mock instance
func NewMockContactCache(ctrl *gomock.Controller) *MockContactCache {
	mock := &MockContactCache{ctrl: ctrl}
	mock.recorder = &MockContactCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockContactCache) EXPECT() *MockContactCacheMockRecorder {
	return m.recorder
}

// Add mocks base method
func (m *MockContactCache) Add(key string, contact models.Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", key, contact)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add
func (mr *MockContactCacheMockRecorder) Add(key, contact interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockContactCache)(nil).Add), key, contact)
}

// Get mocks base method
func (m *MockContactCache) Get(key string) (*models.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(*models.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockContactCacheMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContactCache)(nil).Get), key)
}

// Del mocks base method
func (m *MockContactCache) Del(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del
func (mr *MockContactCacheMockRecorder) Del(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockContactCache)(nil).Del), key)
}

// MockAutopilotProxy is a mock of AutopilotProxy interface
type MockAutopilotProxy struct {
	ctrl     *gomock.Controller
	recorder *MockAutopilotProxyMockRecorder
}

// MockAutopilotProxyMockRecorder is the mock recorder for MockAutopilotProxy
type MockAutopilotProxyMockRecorder struct {
	mock *MockAutopilotProxy
}

// NewMockAutopilotProxy creates a new mock instance
func NewMockAutopilotProxy(ctrl *gomock.Controller) *MockAutopilotProxy {
	mock := &MockAutopilotProxy{ctrl: ctrl}
	mock.recorder = &MockAutopilotProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAutopilotProxy) EXPECT() *MockAutopilotProxyMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockAutopilotProxy) Get(idOrEmail string) ([]models.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", idOrEmail)
	ret0, _ := ret[0].([]models.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockAutopilotProxyMockRecorder) Get(idOrEmail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAutopilotProxy)(nil).Get), idOrEmail)
}

// Upsert mocks base method
func (m *MockAutopilotProxy) Upsert(contact models.Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", contact)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert
func (mr *MockAutopilotProxyMockRecorder) Upsert(contact interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockAutopilotProxy)(nil).Upsert), contact)
}

// MockStore is a mock of Store interface
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockStore) Get(idOrEmail string) ([]models.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", idOrEmail)
	ret0, _ := ret[0].([]models.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockStoreMockRecorder) Get(idOrEmail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStore)(nil).Get), idOrEmail)
}

// Upsert mocks base method
func (m *MockStore) Upsert(contact models.Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", contact)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert
func (mr *MockStoreMockRecorder) Upsert(contact interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockStore)(nil).Upsert), contact)
}
